GET http://localhost:9090/api/ HTTP/1.1


####


GET http://localhost:9090/api/user HTTP/1.1

###

POST http://localhost:9090/api/user HTTP/1.1
Content-Type: application/json

 {
    "id": 107,
    "name": "Asif",
    "income": 5566.5,
    "email": "asif@gmail.com"
  }


### 
GET http://localhost:9090/api/user/102 HTTP/1.1


### 
GET http://localhost:9090/api/user/name/Asif HTTP/1.1


### 
PUT http://localhost:9090/api/user HTTP/1.1
Content-Type: application/json

{
  "id": 456987,
  "name": "Mohammad Asif",
  "income": 5566.5,
  "email": "asif@gmail.com"
}


### 

DELETE http://localhost:9090/api/user/102 HTTP/1.1



### user details 

GET http://localhost:9100/user-details/Yash HTTP/1.1


### making open feign request 

GET http://localhost:9090/api/user-details/alok HTTP/1.1

### making a request with api gateway 

GET http://localhost:8765/REST-WORKS/api/user HTTP/1.1


### making reuqest with api gateway in lower case 

GET http://localhost:8765/rest-works/api/user HTTP/1.1

####

GET http://localhost:8765/rest-works/actuator HTTP/1.1


### making open feign request with api gateway + resilience4j

GET http://localhost:8765/rest-works/api/user-details/alok HTTP/1.1


### invoking contacts mock data 


GET http://localhost:4000/contacts HTTP/1.1

###
GET http://localhost:4000/contacts/2 HTTP/1.1


###
POST http://localhost:4000/contacts HTTP/1.1
Content-Type: application/json

{
  "first_name": "Naveen",
  "last_name": "Kumar",
  "email": "naveen@yandex.ru",
  "gender": "Male",
  "pic": "https://randomuser.me/api/portraits/med/men/3.jpg"
}


###
DELETE http://localhost:4000/contacts/1 HTTP/1.1



### kafka works 

POST http://localhost:9090/kafka HTTP/1.1
Content-Type: application/json

Sample Message from spring boot2



### 

GET https://5gedge.verizon.com/api/mec/eds/mecplatforms
Authorization: bearerAuth MDM4NTQ1MTAtYTNiNi00YjQyLWFkMTMtMTNmN2RlZGI2NGJj